PriorityPlayers:

    - SteamId:  11000010ad1bdde # Dubree
      Priority: 0  # Owner Priority

    - SteamId:  1100001089fd5d9 # Young
      Priority: 0  # Owner Priority

    - SteamId:  1100001056a8b25 # Ben
      Priority: 0  # Owner Priority

DisconnectGrace: 180   # In Seconds (Default = 3 minutes (60 x 3) )
QueueWhenNotFull: true   # true/false (Default = true)
ConnectionTimeout: 120   # In Seconds (Default = 120)
